<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'especie_id',
        'recinto_id',
        'actividad_id',
    ];

    public function especie()
    {
        return $this->belongsTo('App\Models\Especie');
    }

    public function recinto()
    {
        return $this->belongsTo('App\Models\Recinto');
    }

    public function cuidador_animals()
    {
        return $this->hasMany('App\Models\Cuidador_Animal');
    }

    public function actividad()
    {
        return $this->belongsTo('App\Models\Actividad');
    }
}
